# permissions for end users to edit s3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3-aws
    app.kubernetes.io/managed-by: kustomize
  name: s3-editor-role
rules:
- apiGroups:
  - s3-aws.nice-ambien-it.io
  resources:
  - s3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3-aws.nice-ambien-it.io
  resources:
  - s3s/status
  verbs:
  - get
