apiVersion: s3-aws.nice-ambien-it.io/v1alpha1
kind: S3
metadata:
  name: s3-sample
spec:
  # TODO(user): edit the following value to ensure the number
  # of Pods/Instances your Operand must have on cluster
  size: 1
